### PR TITLE
embedded licenses.json file

### PR DESCRIPTION
**Pull request by mathjeff**
downloaded from https://spdx.org/licenses/licenses.json

So that builds using this plugin don't need to redownload this file, to improve determinism and reduce network requests

### CODE REVIEW

**Comment by loosebazooka** [comment]
should make this optional? 
keep `fromRemote` and add `fromEmbedded`(or whatever) and allow the service to be configured with the one that users can pick?

**Comment by mathjeff** [comment]
If we want users to be able to configure the set of known licenses, we should be able to add a parameter to SpdxSbomExtension and to SpdxKnownLicensesService, and pass that parameter from SpdxSbomExtension to SpdxKnownLicensesService to SpdxKnownLicenses

If we give (keep) the option to download the set of known licenses from a url, it could also be nice for us to provide caching to avoid redownloading it whenever the task reruns, although that could be more effort too

Do we have any users that want anything other than an embedded file so we can get more of an idea about what behaviors other than using an embedded file we would want?

**Comment by loosebazooka** [comment]
I think the list is live. https://spdx.org/licenses/ which means we would either have to update our cached version of it on every update remote (this could be automated), but also means a new release.

the other option would be to see if the spdx folks would publish it as a maven artifact that we can consume via the standard dependency resolution mechanims.

**Comment by loosebazooka** [comment]
opened an issue for discussion: https://github.com/spdx/LicenseListPublisher/issues/163

**Comment by mathjeff** [comment]
If there is a user that wants deterministic results and also wants mostly up-to-date results, I think that means we'd either have to keep the embedded licenses file mostly up-to-date or provide some other way for users to update the licenses file

We could even publish our own copies of licenses.json in a new artifact although that wouldn't reduce the total number of times we'd have to publish something as a result of the licenses.json changing

We could allow the user to pass the url of a licenses.json file and use that instead, and allow the user to do their own caching

**Comment by mathjeff** [comment]
> opened an issue for discussion: [spdx/LicenseListPublisher#163](https://github.com/spdx/LicenseListPublisher/issues/163)

sounds good - I guess I won't worry about it too much until we hear back about that

**Comment by loosebazooka** [comment]
So... I guess lets just use embedded for now. And deal with the updates as they come? Perhaps adding a new cron job to check that it has changed (new PR)?

**Comment by mathjeff** [comment]
> So... I guess lets just use embedded for now. And deal with the updates as they come? Perhaps adding a new cron job to check that it has changed (new PR)?

Sounds good to me to have just an embedded licenses list
I don't know of a good way to set up a long-lived cron job to check for future updates though. (My plan was just that users would ask for updates when we need them)

**Comment by loosebazooka** [comment]
I can set up Cron on GitHub

**Review by loosebazooka — APPROVED** [review]

**Comment by goneall** [comment]
You can also get the data from the [license-list-data](https://github.com/spdx/license-list-data) repo.  The repo is tagged by release.  Suggest pulling the latest tag as the main branch is a "work in progress" by the SPDX legal team.

**Pull request merged**
