### PR TITLE
Consider the developer's organization for the package supplier

### LINKED ISSUE #38: Do we want to support the possibility of a `developer` that has an `organization`?
Do we want to support the possibility of a `developer` that has an `organization`?

I think an example is:

https://repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.pom

which contains the text:

```
<developers>
<developer>
<id>JetBrains</id>
<name>JetBrains Team</name>
<organization>JetBrains</organization>
<organizationUrl>http://www.jetbrains.com</organizationUrl>
</developer>
</developers>
```

which is think is causing this text to appear in the sbom:

“supplier" : "Person: Kotlin Team"

maybe it would be better to output this text instead:

“supplier" : "Organization: JetBrains"

_Originally posted by @mathjeff in https://github.com/spdx/spdx-gradle-plugin/pull/29#discussion_r1307635106_

### PR DESCRIPTION
**Pull request by eygraber**
Fixes #38

### CODE REVIEW

**Comment by eygraber** [comment]
I didn't add the organization to the `Person` form of the supplier since [the spec](https://spdx.github.io/spdx-spec/v2.3/package-information/#75-package-supplier-field) only mentions an email.

**Review by loosebazooka — COMMENTED** [review]
Awesome. Anyway we could add this to the functional tests or maybe add move the functionality somewhere more unit testable?

**Comment by eygraber** [comment]
I can make a `MavenPackageSupplierBuilder` class and have unit tests against that

**Comment by loosebazooka** [comment]
Sgtm

**Comment by eygraber** [comment]
Updated with tests

**Review by loosebazooka — APPROVED** [review]

**Comment by loosebazooka** [comment]
Thanks!

**Pull request merged**
